extend:
  - default.yml
output: render
description: Adds relevancy and status buffs to obscure foods!
name: Food Status Effects
data_pack:
  name: food-status-effects
pipeline:
  - plugins.food_status

meta:
  installation_advancement:
    icon:
      item: minecraft:apple
    project_advancement_path: food_status_effects:_installed
